# -*- coding: utf-8 -*-
"""main

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AKiFzK2yVK9NLkODdh8e80jQWFATGU0j
"""

from sorting_algorithms import quick_sort, merge_sort

def main():
    print("Sorting Algorithm Simulator")
    print("1. Quick Sort")
    print("2. Merge Sort")

    choice = int(input("Choose an algorithm (1 or 2): "))
    arr = list(map(int, input("Enter a list of numbers separated by spaces: ").split()))

    if choice == 1:
        print("Quick Sort:", quick_sort(arr))
    elif choice == 2:
        print("Merge Sort:", merge_sort(arr))
    else:
        print("Invalid choice")

if __name__ == "__main__":
    main()