# -*- coding: utf-8 -*-
"""test_sorting

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AKiFzK2yVK9NLkODdh8e80jQWFATGU0j
"""

from sorting_algorithms import quick_sort, merge_sort


def test_quick_sort():
    assert quick_sort([3, 1, 4, 1, 5, 9, 2, 6]) == [1, 1, 2, 3, 4, 5, 6, 9], "Quick Sort Test Failed!"
    print("Quick Sort Test Passed!")

def test_merge_sort():
    assert merge_sort([3, 1, 4, 1, 5, 9, 2, 6]) == [1, 1, 2, 3, 4, 5, 6, 9], "Merge Sort Test Failed!"
    print("Merge Sort Test Passed!")

if __name__ == "__main__":
    test_quick_sort()
    test_merge_sort()